### ISSUE TITLE
Add link to paper

### ISSUE THREAD

**Issue by impredicative** [HongtengXu/PoPPy#1]
Please add a link to your paper https://arxiv.org/abs/1810.10122 into the repo readme. Thanks for providing this toolbox!

**Comment by HongtengXu** [comment]
The link is in the "tutorial" of "Usage" section in the readme. Thanks for your interest.

**Comment by impredicative** [comment]
Ah, I see. I recommend linking to the HTML page of Arxiv, not directly to the PDF. Some readers only want to read the abstract or see related bibliography. Anyway, I will let you decide. Thanks again.
